version: "3"

services:
  app-react:
    # container_name: app-dev
    build: .
    image: app-react
    stdin_open: true
    tty: true
    # build: .
    # command: yarn start
    ports:
      - "3000:3000"
    networks:
      - mern-app
    # volumes:
    #   - ./src:/app/src
  api-server:
    # container_name: backend-dev
    build: ./backend
    image: api-server
    # build: ./backend
    # command: yarn start
    tty: true
    ports:
      - "5000:5000"
    # volumes:
    #   - ./backend:/app/backend
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge
